apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phynd-crm-staging

resources:
- namespace.yaml
- base/web-deployment.yaml
- base/web-service.yaml
- base/worker-deployment.yaml
- base/network-policies.yaml
- base/resource-quota.yaml
- base/pdb.yaml

images:
- digest: sha256:436b2511c19b3d1ddc854006a564d9d397051e29a894504b908423b10c1cf773
  name: ghcr.io/madfam-org/phynd-crm/web
  newName: ghcr.io/madfam-org/phynd-crm/web
- digest: sha256:86031a8675bbc83fc5a281ae2a2f336114822a0211c0e66a6abb16da5b18751a
  name: ghcr.io/madfam-org/phynd-crm/worker
  newName: ghcr.io/madfam-org/phynd-crm/worker

patches:
- path: web-deployment.patch.yaml
- path: worker-deployment.patch.yaml
