apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phyne-crm-staging

resources:
- namespace.yaml
- ../../production/web-deployment.yaml
- ../../production/web-service.yaml
- ../../production/worker-deployment.yaml
- ../../production/network-policies.yaml
- ../../production/resource-quota.yaml
- ../../production/pdb.yaml

images:
- digest: sha256:f8ee5a5857c623cfb29423a1490bce32a569f44deb92434089c7ceee59f3a8ff
  name: ghcr.io/madfam-org/phyne-crm/web
  newName: ghcr.io/madfam-org/phyne-crm/web
- digest: sha256:97ed65ec4c10ae9a7d4fa57a3216cc9c0a475dc248a3ced87b3e856a573f189b
  name: ghcr.io/madfam-org/phyne-crm/worker
  newName: ghcr.io/madfam-org/phyne-crm/worker

patches:
- path: web-deployment.patch.yaml
- path: worker-deployment.patch.yaml
