apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phynd-crm-staging

resources:
- namespace.yaml
- external-secret.yaml
- base/web-deployment.yaml
- base/web-service.yaml
- base/worker-deployment.yaml
- base/network-policies.yaml
- base/resource-quota.yaml
- base/pdb.yaml

images:
- digest: sha256:52d183d3f8e0746685e1057e7f5ef0cd1d192e8a5cddd155c06c562c5b6e034a
  name: ghcr.io/madfam-org/phynd-crm/web
  newName: ghcr.io/madfam-org/phynd-crm/web
- digest: sha256:2a4f77774853132b945392e6f41e8e8e7c6afd2be6ef0bbb1d3fa00af6fd6616
  name: ghcr.io/madfam-org/phynd-crm/worker
  newName: ghcr.io/madfam-org/phynd-crm/worker

patches:
- path: web-deployment.patch.yaml
- path: worker-deployment.patch.yaml
