apiVersion: apps/v1
kind: Deployment
metadata:
  name: phyne-crm-web
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: web
          envFrom:
            - secretRef:
                name: phyne-crm-staging-secrets
            - secretRef:
                name: phyne-acca-staging-secrets
                optional: true
