apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phyne-crm

resources:
- namespace.yaml
- web-deployment.yaml
- web-service.yaml
- worker-deployment.yaml
- network-policies.yaml
- resource-quota.yaml
- pdb.yaml

images:
- name: ghcr.io/madfam-org/phyne-crm/web
  newName: ghcr.io/madfam-org/phyne-crm/web
  digest: sha256:6da9793b3e9d64bec1cb15ea3cf27d36728bd453f0fd45f8b847834c07bbca04
- name: ghcr.io/madfam-org/phyne-crm/worker
  newName: ghcr.io/madfam-org/phyne-crm/worker
  digest: sha256:d532559f160f56228837d16fc34d551fb1a9528dbfa5024c4136b36634f04105
