apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phynd-crm

resources:
- external-secret.yaml
- namespace.yaml
- web-deployment.yaml
- web-service.yaml
- worker-deployment.yaml
- network-policies.yaml
- resource-quota.yaml
- pdb.yaml

images:
- digest: sha256:6673a171ef8a7bbbee3adb2d9242941816336cd6bbd6c8a2953c9f2ce256c6da
  name: ghcr.io/madfam-org/phynd-crm/web
  newName: ghcr.io/madfam-org/phynd-crm/web
- digest: sha256:a834b5d2f051ffd48bf795c0e574ded476c25587ac22376c3cbe61558d0ed0ff
  name: ghcr.io/madfam-org/phynd-crm/worker
  newName: ghcr.io/madfam-org/phynd-crm/worker
