---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: phyne-crm-quota
  namespace: phyne-crm
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "3"
    limits.memory: 4Gi
    pods: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: phyne-crm-limits
  namespace: phyne-crm
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      type: Container
