apiVersion: v1
kind: Service
metadata:
  name: phynd-crm-web
  namespace: phynd-crm
spec:
  selector:
    app: phynd-crm-web
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
